security:

    providers:
        our_db_provider:
            entity:
                class: App\Entity\Utilisateurs
                property: username

    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            #logout_on_user_change: false
            logout:
                path: logout
                target: home
            guard:
                authenticators:
                    - App\Security\UserAuthenticator

    encoders:
        App\Entity\Utilisateurs:
            algorithm: bcrypt

    access_control:
        - {path: ^/admin, roles: ROLE_ADMIN}